import type { TutorialStep } from "../engine-types";

export const bonusSteps: TutorialStep[] = [
  {
    id: "pessoal-bonus-eligibility",
    kind: "narration",
    scene: "pessoal-hub",
    title: "Bônus",
    description: "Colaboradores bonificáveis acompanham o cálculo do bônus por aqui.",
    placement: "center",
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-tap",
    kind: "interactive",
    scene: "pessoal-hub",
    highlight: "pessoalGridCardBonus",
    title: "Meu Bônus",
    description: "Toque para ver o detalhamento do bônus do mês.",
    expectedAction: "tap",
    placement: "bottom",
    pulseTarget: true,
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-period-card",
    kind: "showcase",
    scene: "meu-bonus",
    highlight: "pessoalBonusPeriodCard",
    title: "Período atual",
    description: "Valor estimado do bônus do período em apuração.",
    placement: "bottom",
    autoAdvanceMs: 3500,
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-rules",
    kind: "showcase",
    scene: "meu-bonus",
    highlight: "pessoalBonusRules",
    title: "Regras",
    description: "Como o bônus é calculado: assiduidade, performance e comissão.",
    placement: "bottom",
    autoAdvanceMs: 3000,
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-amounts",
    kind: "showcase",
    scene: "meu-bonus",
    highlight: "pessoalBonusAmount",
    title: "Valores",
    description: "Base, descontos e líquido estimado.",
    placement: "top",
    autoAdvanceMs: 3000,
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-historico-tap",
    kind: "interactive",
    scene: "meu-bonus",
    highlight: "pessoalBonusNavHistorico",
    title: "Histórico",
    description: "Toque para ver bônus dos meses anteriores.",
    expectedAction: "tap",
    placement: "top",
    pulseTarget: true,
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-historico-overview",
    kind: "showcase",
    scene: "meu-bonus-historico",
    title: "Histórico de bônus",
    description: "Todos os bônus pagos, com valor e status de cada período.",
    placement: "center",
    autoAdvanceMs: 3000,
    condition: (ctx) => ctx.isBonifiable,
  },
];
