import type { TutorialStep } from "../engine-types";

export const bonusSteps: TutorialStep[] = [
  {
    id: "pessoal-bonus-tap",
    kind: "interactive",
    scene: "pessoal-hub",
    highlight: "pessoalGridCardBonus",
    title: "Meu Bônus",
    description: "Toque em \"Meu Bônus\" para abrir o detalhamento do período atual.",
    expectedAction: "tap",
    placement: "bottom",
    pulseTarget: true,
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-eligibility",
    kind: "showcase",
    scene: "meu-bonus",
    title: "Meu Bônus",
    description:
      "Esta é a tela Meu Bônus: é aqui que você acompanha o bônus de produção do período atual. Vamos ver, passo a passo, como ele é calculado e o que faz o valor subir ou descer.",
    placement: "center",
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-period-card",
    kind: "showcase",
    scene: "meu-bonus",
    highlight: "pessoalBonusPeriodCard",
    title: "Período em apuração",
    description:
      "O bônus é apurado por período mensal — aqui, 26/04 a 25/05. O cálculo é provisório e vai mudando até o fechamento; o pagamento sai no 5º dia útil do mês seguinte.",
    placement: "bottom",
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-value",
    kind: "showcase",
    scene: "meu-bonus",
    highlight: "pessoalBonusValue",
    title: "Valor Líquido: o que você recebe",
    description:
      "Este é o valor estimado que cai no seu bolso neste período. Ele parte de um Valor Base, soma os extras (assiduidade) e subtrai os descontos (faltas/atrasos). Vamos ver de onde vem cada parte.",
    placement: "bottom",
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-level",
    kind: "showcase",
    scene: "meu-bonus",
    highlight: "pessoalBonusLevel",
    title: "Cargo + Nível de Performance",
    description:
      "O Valor Base nasce do seu cargo e cresce conforme o seu Nível de Performance. Quanto maior o nível, maior o bônus — subir de nível é a forma mais forte de aumentar o valor que você recebe.",
    placement: "top",
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-tasks",
    kind: "showcase",
    scene: "meu-bonus",
    highlight: "pessoalBonusTasks",
    title: "Tarefas e ponderação",
    description:
      "As tarefas finalizadas no setor são ponderadas e divididas entre os colaboradores elegíveis. Aqui foram 24 tarefas (21,50 ponderadas) para 12 pessoas — média de 1,79 por colaborador. Quanto maior essa média, maior o Valor Base de todo mundo.",
    placement: "top",
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-bonification",
    kind: "showcase",
    scene: "meu-bonus",
    highlight: "pessoalBonusBonification",
    title: "Bonificação das tarefas",
    description:
      "É o status da bonificação que define quanto cada tarefa pesa: Integral conta 1.0, Parcial conta 0.5, Sem Bonificação conta 0 e Suspensa fica de fora do cálculo. Por isso a quantidade ponderada (21,50) é menor que o total de tarefas (24).",
    placement: "top",
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-rules",
    kind: "interactive",
    scene: "meu-bonus",
    highlight: "pessoalBonusRules",
    title: "Regras do bônus",
    description:
      "Toque em \"Regras do Bônus\" para abrir o resumo completo de extras e descontos.",
    expectedAction: "tap",
    placement: "bottom",
    pulseTarget: true,
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-rules-modal",
    kind: "showcase",
    scene: "meu-bonus",
    sceneState: { bonusRulesModal: true },
    highlight: "pessoalBonusRulesModal",
    title: "Assiduidade, faltas e atestados",
    description:
      "Aqui estão as regras: cada dia sem correção, sem batida faltando e sem atrasos rende +1% de assiduidade (uma correção justificada por atestado mantém o dia); faltas e atrasos sem justificativa descontam 25%, 50% ou 100% conforme as horas e reduzem a assiduidade (perde o dia, 50% ou 100%); atestados são mais leves e têm regra de perdão; e tarefas suspensas saem do cálculo.",
    placement: "center",
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-rules-close",
    kind: "showcase",
    scene: "meu-bonus",
    highlight: "pessoalBonusRules",
    title: "Voltar ao detalhamento",
    description:
      "Pode fechar as regras a qualquer momento e voltar para o detalhamento do seu bônus. Vamos seguir vendo como tudo se junta no valor final.",
    placement: "bottom",
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-amounts",
    kind: "showcase",
    scene: "meu-bonus",
    highlight: "pessoalBonusAmount",
    title: "Juntando tudo",
    description:
      "Aqui você vê a conta fechada: Valor Base, a assiduidade somando, as faltas/atrasos descontando e o Valor Líquido no fim. Atestados acima dos limites também entram como desconto nesta lista.",
    placement: "top",
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-simulacao-tap",
    kind: "interactive",
    scene: "meu-bonus",
    highlight: "pessoalBonusNavSimulacao",
    title: "Simular o seu bônus",
    description:
      "Quer saber quanto ganharia se subisse de nível ou de cargo? Toque em \"Simulação\" para abrir o simulador e projetar o seu bônus antes do fechamento.",
    expectedAction: "tap",
    placement: "top",
    pulseTarget: true,
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-simulacao-overview",
    kind: "showcase",
    scene: "meu-bonus-simulacao",
    highlight: "pessoalBonusSimControls",
    title: "Simulador de bônus",
    description:
      "Esta é a tela de simulação. Aqui você monta um cenário \"e se?\": muda a quantidade de tarefas, o cargo e o nível de desempenho, e o app recalcula na hora o bônus que você receberia. Nada disso altera o seu bônus real — é só uma projeção.",
    placement: "bottom",
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-simulacao-tasks",
    kind: "showcase",
    scene: "meu-bonus-simulacao",
    highlight: "pessoalBonusSimTasks",
    title: "Tarefas a simular",
    description:
      "Comece pelas tarefas ponderadas do setor. O campo já vem com o valor do período atual (21,5) — aumente ou diminua para ver o efeito, ou toque no botão de recarregar para voltar ao valor real.",
    placement: "bottom",
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-simulacao-cargo",
    kind: "showcase",
    scene: "meu-bonus-simulacao",
    highlight: "pessoalBonusSimPosition",
    title: "E se eu mudasse de cargo?",
    description:
      "Você pode escolher o seu cargo atual ou os próximos da carreira. Aqui simulamos uma promoção para \"Pleno III\" — cargos mais altos têm um Valor Base maior, então o bônus projetado sobe junto.",
    placement: "bottom",
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-simulacao-nivel",
    kind: "showcase",
    scene: "meu-bonus-simulacao",
    highlight: "pessoalBonusSimLevel",
    title: "E se eu subisse de nível?",
    description:
      "Use as setas para testar cada Nível de Desempenho, de 1 a 5. Subimos para o Nível 5 nesta simulação: como o nível multiplica o Valor Base, é o que mais faz o bônus projetado crescer.",
    placement: "bottom",
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-simulacao-resultado",
    kind: "showcase",
    scene: "meu-bonus-simulacao",
    highlight: "pessoalBonusSimResult",
    title: "Resultado da simulação",
    description:
      "Este é o bônus projetado com as suas escolhas, com o resumo logo abaixo: cargo, nível, tarefas, colaboradores elegíveis e a média por colaborador. Use o simulador para definir metas — quanto preciso entregar para chegar no valor que quero?",
    placement: "top",
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-simulacao-voltar",
    kind: "showcase",
    scene: "meu-bonus",
    title: "Voltar ao detalhamento",
    description:
      "Pronto: terminamos a simulação. Volte ao detalhamento do bônus para ver o histórico dos meses anteriores.",
    placement: "center",
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-historico-tap",
    kind: "interactive",
    scene: "meu-bonus",
    highlight: "pessoalBonusNavHistorico",
    title: "Ver o histórico",
    description: "Toque em \"Histórico\" para conferir os bônus dos meses anteriores.",
    expectedAction: "tap",
    placement: "top",
    pulseTarget: true,
    condition: (ctx) => ctx.isBonifiable,
  },
  {
    id: "pessoal-bonus-historico-overview",
    kind: "showcase",
    scene: "meu-bonus-historico",
    highlight: "pessoalBonusHistory",
    title: "Histórico de bônus",
    description:
      "Cada linha é um período com o valor recebido naquele mês: de um lado o Período, do outro o Valor. Use o histórico para acompanhar a evolução do seu bônus mês a mês.",
    placement: "center",
    condition: (ctx) => ctx.isBonifiable,
  },
];
