import type { TutorialStep } from "../engine-types";

export const cronogramaSteps: TutorialStep[] = [
  {
    id: "drawer-intro",
    kind: "narration",
    scene: "home",
    title: "Menu lateral",
    description: "Vamos abrir o menu lateral para conhecer as seções do app.",
    placement: "center",
  },
  {
    id: "drawer-overview",
    kind: "interactive",
    scene: "home",
    highlight: "chromeDrawerToggle",
    title: "Abrir menu",
    description: "Toque no botão no canto superior esquerdo.",
    expectedAction: "tap",
    placement: "bottom",
    pulseTarget: true,
  },
  {
    id: "drawer-cronograma",
    kind: "interactive",
    scene: "home",
    sceneState: { drawer: "menu" },
    highlight: "drawerCronograma",
    title: "Cronograma",
    description: "Toque em \"Cronograma\" para abrir a lista de tarefas.",
    expectedAction: "tap",
    placement: "bottom",
    pulseTarget: true,
  },
  {
    id: "cronograma-list",
    kind: "showcase",
    scene: "cronograma",
    title: "Lista de tarefas",
    description: "Todas as tarefas do seu setor aparecem aqui, organizadas por prazo.",
    placement: "center",
    autoAdvanceMs: 3000,
  },
  {
    id: "cronograma-search",
    kind: "showcase",
    scene: "cronograma",
    highlight: "cronogramaSearch",
    title: "Buscar tarefa",
    description: "Use a busca para encontrar uma tarefa específica.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "cronograma-filters",
    kind: "showcase",
    scene: "cronograma",
    highlight: "cronogramaFilters",
    title: "Filtros",
    description: "Filtre por status, cliente, prazo, e mais.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "cronograma-columns",
    kind: "showcase",
    scene: "cronograma",
    highlight: "cronogramaColumnVisibility",
    title: "Colunas",
    description: "Escolha quais colunas você quer ver na tabela.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "cronograma-status-legend",
    kind: "narration",
    scene: "cronograma",
    title: "Cores dos status",
    description: "Verde = em produção · Amarelo = aguardando · Vermelho = atrasado · Cinza = concluído.",
    placement: "center",
  },
  {
    id: "cronograma-deadline-info",
    kind: "narration",
    scene: "cronograma",
    title: "Prazos",
    description: "Tarefas com prazo curto ou vencido ficam destacadas com bordas coloridas.",
    placement: "center",
  },
  {
    id: "cronograma-tap-task",
    kind: "interactive",
    scene: "cronograma",
    highlight: "cronogramaFirstTask",
    title: "Abrir uma tarefa",
    description: "Toque em qualquer tarefa para ver os detalhes.",
    expectedAction: "tap",
    placement: "bottom",
    pulseTarget: true,
  },
];
