import type { TutorialStep } from "../engine-types";

export const cronogramaSteps: TutorialStep[] = [
  {
    id: "drawer-intro",
    kind: "narration",
    scene: "home",
    title: "Menu lateral",
    description: "Vamos abrir o menu lateral para conhecer as seções do app.",
    placement: "center",
  },
  {
    id: "drawer-overview",
    kind: "interactive",
    scene: "home",
    highlight: "chromeDrawerToggle",
    title: "Abrir menu",
    description: "Toque no botão no canto superior esquerdo.",
    expectedAction: "tap",
    placement: "bottom",
    pulseTarget: true,
  },
  {
    id: "drawer-cronograma",
    kind: "interactive",
    scene: "home",
    sceneState: { drawer: "menu" },
    highlight: "drawerCronograma",
    title: "Cronograma",
    description: "Toque em \"Cronograma\" para abrir a lista de tarefas.",
    expectedAction: "tap",
    placement: "bottom",
    pulseTarget: true,
  },
  {
    id: "cronograma-list",
    kind: "showcase",
    scene: "cronograma",
    title: "Lista de tarefas",
    description: "As tarefas de produção aparecem aqui. Cada linha mostra a logomarca (com a cor da pintura), o número de série e a contagem regressiva até o prazo.",
    placement: "center",
    // Don't dim — this step is about reading the whole list (and its row colors).
    dimBackground: false,
  },
  {
    id: "cronograma-search",
    kind: "showcase",
    scene: "cronograma",
    highlight: "cronogramaSearch",
    title: "Buscar tarefa",
    description: "Use a busca para encontrar uma tarefa por nome, número de série ou cliente.",
    placement: "bottom",
  },
  {
    id: "cronograma-sectors",
    kind: "showcase",
    scene: "cronograma",
    highlight: "cronogramaSectorToggle",
    title: "Todos os setores",
    description: "Por padrão você vê apenas as tarefas do seu setor. Toque aqui para ver as tarefas de todos os setores da empresa.",
    placement: "bottom",
  },
  {
    id: "cronograma-columns",
    kind: "showcase",
    scene: "cronograma",
    highlight: "cronogramaColumnVisibility",
    title: "Colunas",
    description: "Escolha quais colunas você quer ver na tabela.",
    placement: "bottom",
  },
  {
    id: "cronograma-filters",
    kind: "showcase",
    scene: "cronograma",
    highlight: "cronogramaFilters",
    title: "Filtros",
    description: "Filtre por status, cliente, prazo, e mais.",
    placement: "bottom",
  },
  {
    id: "cronograma-status-legend",
    kind: "narration",
    scene: "cronograma",
    title: "Cores das linhas",
    description: "A cor de fundo da linha mostra a urgência das tarefas em produção — Verde: mais de 4h até o prazo · Laranja: menos de 4h · Vermelho: prazo vencido · Cinza: em preparação, aguardando ou concluída.",
    placement: "center",
  },
  {
    id: "cronograma-deadline-info",
    kind: "narration",
    scene: "cronograma",
    title: "Priorize pelo prazo",
    description: "Assim você identifica num relance o que precisa de atenção: tarefas laranja e vermelhas são prioridade.",
    placement: "center",
  },
  {
    id: "cronograma-tap-task",
    kind: "interactive",
    scene: "cronograma",
    highlight: "cronogramaFirstTask",
    title: "Abrir uma tarefa",
    description: "Toque em qualquer tarefa para ver os detalhes.",
    expectedAction: "tap",
    placement: "bottom",
    pulseTarget: true,
  },
];
