import type { TutorialStep } from "../engine-types";

export const episSteps: TutorialStep[] = [
  {
    id: "pessoal-epis-tap",
    kind: "interactive",
    scene: "pessoal-hub",
    highlight: "pessoalGridCardEpis",
    title: "Meus EPIs",
    description: "Toque para acessar EPIs entregues e solicitar novos.",
    expectedAction: "tap",
    placement: "bottom",
    pulseTarget: true,
  },
  {
    id: "pessoal-epis-list",
    kind: "showcase",
    scene: "meus-epis",
    highlight: "pessoalEpis",
    title: "Lista de EPIs",
    description: "EPIs entregues, pendentes e aguardando assinatura.",
    placement: "center",
    autoAdvanceMs: 3000,
  },
  {
    id: "pessoal-epis-request-open",
    kind: "showcase",
    scene: "meus-epis",
    highlight: "pessoalEpisRequestButton",
    title: "Solicitar EPI",
    description: "Toque aqui para abrir o pedido de um novo item.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "pessoal-epis-sign-card",
    kind: "showcase",
    scene: "epis-detail",
    highlight: "pessoalEpisDetailSign",
    title: "Confirmação de recebimento",
    description: "EPIs entregues exigem sua confirmação biométrica.",
    placement: "top",
    autoAdvanceMs: 3500,
  },
  {
    id: "pessoal-epis-sign-biometric",
    kind: "showcase",
    scene: "epis-detail",
    sceneState: { epiSignStage: "biometric" },
    highlight: "pessoalEpisBiometric",
    title: "Biometria",
    description: "Toque com seu dedo ou rosto para confirmar.",
    placement: "top",
    autoAdvanceMs: 2500,
  },
  {
    id: "pessoal-epis-sign-receipt",
    kind: "showcase",
    scene: "epis-detail",
    sceneState: { epiSignStage: "done" },
    title: "Confirmado!",
    description: "Pronto, o recebimento foi registrado.",
    placement: "center",
    autoAdvanceMs: 2500,
  },
];
