import type { TutorialStep } from "../engine-types";

export const homeSteps: TutorialStep[] = [
  {
    id: "welcome",
    kind: "narration",
    scene: "home",
    title: "Bem-vindo ao Ankaa!",
    description: "Vamos te mostrar o app em poucos minutos. Você pode pular este tutorial a qualquer momento pelo X no canto.",
    placement: "center",
    ctaLabel: "Vamos lá",
  },
  {
    id: "tutorial-pacing",
    kind: "narration",
    scene: "home",
    title: "Sobre o tutorial",
    description: "Cada passo destaca um item da tela. Toque em \"Continuar\" para avançar, ou no item destacado quando pedirmos uma interação.",
    placement: "center",
  },
  {
    id: "home-greeting",
    kind: "showcase",
    scene: "home",
    highlight: "homeGreeting",
    title: "Saudação",
    description: "Aqui aparecem seu nome, a data e o horário atual.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "home-favorites",
    kind: "showcase",
    scene: "home",
    highlight: "homeFavorites",
    title: "Atalhos rápidos",
    description: "Acesse os locais mais importantes do app com um toque.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "home-widgets-intro",
    kind: "narration",
    scene: "home",
    highlight: "homeWidgetList",
    title: "Widgets",
    description: "Seu painel pode ser personalizado com widgets. Vamos te mostrar como.",
    placement: "top",
  },
  {
    id: "home-edit-panel",
    kind: "interactive",
    scene: "home",
    highlight: "homeEditPanelButton",
    title: "Editar painel",
    description: "Toque em \"Editar painel\" para começar a personalizar.",
    expectedAction: "tap",
    placement: "bottom",
    pulseTarget: true,
  },
  {
    id: "home-edit-toolbar",
    kind: "showcase",
    scene: "home",
    sceneState: { homeEditMode: true, homeWidgetPresent: true },
    highlight: "homeEditToolbar",
    title: "Barra de edição",
    description: "Daqui você adiciona, remove ou reorganiza os widgets.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "home-widget-drag",
    kind: "showcase",
    scene: "home",
    sceneState: { homeEditMode: true, homeWidgetPresent: true },
    highlight: "homeFirstWidgetTile",
    title: "Arrastar widget",
    description: "Cada widget pode ser arrastado para reordenar.",
    placement: "top",
    autoAdvanceMs: 3000,
  },
  {
    id: "home-widget-options",
    kind: "showcase",
    scene: "home",
    sceneState: { homeEditMode: true, homeWidgetPresent: true },
    highlight: "homeWidgetMoreActions",
    title: "Opções do widget",
    description: "Os 3 pontos abrem configurações de cada widget.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "home-add-widget",
    kind: "interactive",
    scene: "home",
    sceneState: { homeEditMode: true, homeWidgetPresent: false },
    highlight: "homeAddWidgetButton",
    title: "Adicionar widget",
    description: "Toque em \"Adicionar widget\" para abrir o catálogo.",
    expectedAction: "tap",
    placement: "top",
    pulseTarget: true,
  },
  {
    id: "home-widget-catalog",
    kind: "interactive",
    scene: "home",
    sceneState: { homeEditMode: true, homeAddWidgetSheet: true, homeWidgetPresent: false },
    highlight: "homeAddWidgetCatalogTarefas",
    title: "Escolher widget",
    description: "Selecione \"Tarefas\" para adicionar à sua tela.",
    expectedAction: "tap",
    placement: "top",
    pulseTarget: true,
  },
  {
    id: "home-widget-added",
    kind: "showcase",
    scene: "home",
    sceneState: { homeEditMode: true, homeWidgetPresent: true },
    highlight: "homeFirstWidgetTile",
    title: "Widget adicionado!",
    description: "O widget \"Tarefas\" agora aparece no seu painel.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "home-save-edit",
    kind: "interactive",
    scene: "home",
    sceneState: { homeEditMode: true, homeWidgetPresent: true },
    highlight: "homeSaveEditButton",
    title: "Salvar alterações",
    description: "Toque em \"Salvar\" para confirmar a edição.",
    expectedAction: "tap",
    placement: "bottom",
    pulseTarget: true,
  },
  {
    id: "home-save-done",
    kind: "narration",
    scene: "home",
    sceneState: { homeWidgetPresent: true },
    title: "Painel salvo",
    description: "Pronto! Seu painel está personalizado.",
    placement: "center",
  },
  {
    id: "notifications-intro",
    kind: "narration",
    scene: "home",
    title: "Notificações",
    description: "Vamos ver onde ficam as notificações.",
    placement: "center",
  },
  {
    id: "notifications-bell-tap",
    kind: "interactive",
    scene: "home",
    highlight: "chromeNotificationsBell",
    title: "Sino de notificações",
    description: "Toque no sino no canto superior direito.",
    expectedAction: "tap",
    placement: "bottom",
    pulseTarget: true,
  },
  {
    id: "notifications-list",
    kind: "showcase",
    scene: "home",
    sceneState: { drawer: "notifications" },
    title: "Suas notificações",
    description: "Aqui aparecem alertas de tarefas, recortes prontos e comunicados.",
    placement: "center",
    autoAdvanceMs: 3500,
  },
  {
    id: "notifications-close",
    kind: "interactive",
    scene: "home",
    sceneState: { drawer: "notifications" },
    highlight: "notificationsCloseBackdrop",
    title: "Fechar notificações",
    description: "Toque fora do painel para fechar.",
    expectedAction: "tap",
    placement: "center",
  },
];
