import type { TutorialStep } from "../engine-types";

export const homeSteps: TutorialStep[] = [
  {
    id: "welcome",
    kind: "narration",
    scene: "home",
    title: "Bem-vindo ao Ankaa!",
    description: "Vamos te mostrar o app em poucos minutos. Você pode pular este tutorial a qualquer momento pelo X no canto.",
    placement: "bottom",
    ctaLabel: "Vamos lá",
  },
  {
    id: "tutorial-pacing",
    kind: "narration",
    scene: "home",
    title: "Sobre o tutorial",
    description: "Cada passo destaca um item da tela. Toque em \"Continuar\" para avançar, ou no item destacado quando pedirmos uma interação.",
    placement: "bottom",
  },
  {
    id: "home-greeting",
    kind: "showcase",
    scene: "home",
    sceneState: { homeWidgetPresent: false },
    highlight: "homeGreeting",
    title: "Seu cabeçalho",
    description: "No topo da tela inicial fica a saudação com o seu nome, um relógio que atualiza em tempo real e a data de hoje.",
    placement: "bottom",
  },
  {
    id: "home-widgets-intro",
    kind: "narration",
    scene: "home",
    sceneState: { homeWidgetPresent: false },
    highlight: "homeWidgetList",
    title: "Widgets",
    description: "Seu painel já vem com widgets do seu setor e pode ser personalizado. Vamos adicionar mais um.",
    placement: "top",
  },
  {
    id: "home-edit-panel",
    kind: "interactive",
    scene: "home",
    sceneState: { homeWidgetPresent: false },
    highlight: "homeEditPanelButton",
    title: "Editar painel",
    description: "Toque em \"Editar\" para começar a personalizar.",
    expectedAction: "tap",
    placement: "bottom",
    pulseTarget: true,
  },
  {
    id: "home-edit-toolbar",
    kind: "showcase",
    scene: "home",
    sceneState: { homeEditMode: true, homeWidgetPresent: false },
    highlight: "homeEditToolbar",
    title: "Barra de edição",
    description: "Daqui você adiciona, descarta ou salva as alterações do painel.",
    placement: "bottom",
  },
  {
    id: "home-add-widget",
    kind: "interactive",
    scene: "home",
    sceneState: { homeEditMode: true, homeWidgetPresent: false },
    highlight: "homeAddWidgetButton",
    title: "Adicionar widget",
    description: "Toque em \"Adicionar\" para abrir a galeria de widgets.",
    expectedAction: "tap",
    placement: "top",
    pulseTarget: true,
  },
  {
    id: "home-widget-catalog",
    kind: "interactive",
    scene: "home",
    sceneState: { homeEditMode: true, homeAddWidgetSheet: true, homeWidgetPresent: false },
    highlight: "homeAddWidgetCatalogTarefas",
    title: "Escolher widget",
    description: "Selecione \"Tarefas\" para adicionar ao seu painel.",
    expectedAction: "tap",
    // The widget gallery fills most of the screen, so the tooltip drops to the
    // bottom (instead of anchoring above the highlighted "Tarefas" card, which
    // would cover the sheet header). The spotlight + tap on the card stay live.
    placement: "bottom",
    tooltipPinToScreenBottom: true,
    pulseTarget: true,
  },
  {
    id: "home-widget-added",
    kind: "showcase",
    scene: "home",
    sceneState: { homeEditMode: true, homeWidgetPresent: true },
    highlight: "homeFirstWidgetTile",
    title: "Widget adicionado!",
    description: "Pronto! O widget \"Tarefas\" foi adicionado ao final do seu painel.",
    placement: "bottom",
  },
  {
    id: "home-widget-drag",
    kind: "showcase",
    scene: "home",
    sceneState: { homeEditMode: true, homeWidgetPresent: true },
    highlight: "homeFirstWidgetTile",
    title: "Arrastar widget",
    description: "Pressione e segure um widget para arrastá-lo e reordenar o painel.",
    placement: "top",
  },
  {
    id: "home-widget-options",
    kind: "showcase",
    scene: "home",
    sceneState: { homeEditMode: true, homeWidgetPresent: true },
    highlight: "homeWidgetMoreActions",
    title: "Opções do widget",
    description: "O botão de 3 pontos, no canto inferior do widget, abre as configurações de cada widget.",
    placement: "bottom",
  },
  {
    id: "home-save-edit",
    kind: "interactive",
    scene: "home",
    sceneState: { homeEditMode: true, homeWidgetPresent: true },
    highlight: "homeSaveEditButton",
    title: "Salvar alterações",
    description: "Toque em \"Salvar\" para confirmar a edição.",
    expectedAction: "tap",
    placement: "bottom",
    pulseTarget: true,
  },
  {
    id: "home-save-done",
    kind: "narration",
    scene: "home",
    sceneState: { homeWidgetPresent: true },
    title: "Painel salvo",
    description: "Pronto! Seu painel está personalizado.",
    placement: "bottom",
  },
  {
    id: "notifications-intro",
    kind: "narration",
    scene: "home",
    title: "Notificações",
    description: "Vamos ver onde ficam as notificações.",
    placement: "bottom",
  },
  {
    id: "notifications-bell-tap",
    kind: "interactive",
    scene: "home",
    highlight: "chromeNotificationsBell",
    title: "Sino de notificações",
    description: "Toque no sino no canto superior direito.",
    expectedAction: "tap",
    placement: "bottom",
    pulseTarget: true,
  },
  {
    id: "notifications-list",
    kind: "showcase",
    scene: "home",
    sceneState: { drawer: "notifications" },
    title: "Suas notificações",
    description: "Aqui aparecem alertas de tarefas, recortes prontos e comunicados.",
    placement: "bottom",
  },
  {
    id: "notifications-close",
    kind: "interactive",
    scene: "home",
    sceneState: { drawer: "notifications" },
    highlight: "notificationsCloseBackdrop",
    title: "Fechar notificações",
    description: "Toque na parte esquerda para fechar.",
    expectedAction: "tap",
    placement: "bottom",
    pulseTarget: true,
  },
];
