import type { TutorialStep } from "../engine-types";

export const incluirPontoSteps: TutorialStep[] = [
  {
    id: "pessoal-pontos-incluir-overview",
    kind: "showcase",
    scene: "incluir-ponto",
    highlight: "pessoalPontosIncluirPage",
    title: "Incluir Ponto",
    description: "Registre uma batida pelo celular quando o relógio do escritório falha.",
    placement: "center",
    autoAdvanceMs: 3000,
  },
  {
    id: "pessoal-pontos-incluir-cta",
    kind: "showcase",
    scene: "incluir-ponto",
    highlight: "pessoalPontosIncluirCta",
    title: "Nova inclusão",
    description: "Este botão inicia a captura de uma nova batida com GPS.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "pessoal-pontos-incluir-list-card",
    kind: "showcase",
    scene: "incluir-ponto",
    highlight: "pessoalPontosIncluirListCard",
    title: "Últimos registros",
    description: "Suas inclusões recentes com status (processando, aceita, rejeitada).",
    placement: "top",
    autoAdvanceMs: 3000,
  },
  {
    id: "pessoal-pontos-incluir-row-expand",
    kind: "interactive",
    scene: "incluir-ponto",
    highlight: "pessoalPontosIncluirFirstRow",
    title: "Expandir registro",
    description: "Toque na primeira linha para ver detalhes (mapa, precisão, endereço).",
    expectedAction: "tap",
    placement: "bottom",
    pulseTarget: true,
  },
  {
    id: "pessoal-pontos-incluir-row-details",
    kind: "showcase",
    scene: "incluir-ponto",
    sceneState: { incluirPontoExpandedRow: 0 },
    highlight: "pessoalPontosIncluirFirstRow",
    title: "Detalhes",
    description: "Aqui você confere o local exato, precisão do GPS e motivo de rejeição (se houver).",
    placement: "top",
    autoAdvanceMs: 3500,
  },
];
