import type { TutorialStep } from "../engine-types";

export const justificarSteps: TutorialStep[] = [
  {
    id: "pessoal-pontos-justify-list",
    kind: "showcase",
    scene: "justificar-list",
    highlight: "pessoalPontosJustifyPage",
    title: "Dias em aberto",
    description: "Aqui aparecem os dias com saldo negativo, divididos entre abertos e encerrados.",
    placement: "center",
    autoAdvanceMs: 3000,
  },
  {
    id: "pessoal-pontos-justify-row-tap",
    kind: "interactive",
    scene: "justificar-list",
    highlight: "pessoalPontosJustifyFirstRow",
    title: "Justificar este dia",
    description: "Toque na linha para abrir o formulário de justificativa.",
    expectedAction: "tap",
    placement: "bottom",
    pulseTarget: true,
  },
  {
    id: "pessoal-pontos-justify-form-overview",
    kind: "showcase",
    scene: "justificar-form",
    highlight: "pessoalPontosJustifyForm",
    title: "Formulário de justificativa",
    description: "Preencha tipo, período, motivo e anexe a documentação.",
    placement: "center",
    autoAdvanceMs: 3000,
  },
  {
    id: "pessoal-pontos-justify-motivo",
    kind: "showcase",
    scene: "justificar-form",
    highlight: "pessoalPontosJustifyMotivo",
    title: "Motivo",
    description: "Atestado médico, licença paternidade, falta justificada, etc.",
    placement: "top",
    autoAdvanceMs: 3000,
  },
  {
    id: "pessoal-pontos-justify-submit",
    kind: "interactive",
    scene: "justificar-form",
    highlight: "pessoalPontosJustifySubmit",
    title: "Enviar",
    description: "Toque para enviar a justificativa.",
    expectedAction: "tap",
    placement: "top",
    pulseTarget: true,
  },
];
