import type { TutorialStep } from "../engine-types";

export const perfilSteps: TutorialStep[] = [
  {
    id: "preferences-theme-card",
    kind: "showcase",
    scene: "preferencias",
    highlight: "preferencesThemeCard",
    title: "Tema",
    description: "Escolha entre tema claro, escuro ou seguir o sistema.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "preferences-notifications-tap",
    kind: "interactive",
    scene: "preferencias",
    highlight: "preferencesNotificationsCard",
    title: "Preferências de notificação",
    description: "Toque para configurar canais por tipo de evento.",
    expectedAction: "tap",
    placement: "bottom",
    pulseTarget: true,
  },
  {
    id: "notifications-legend",
    kind: "showcase",
    scene: "notif-prefs",
    highlight: "notifPrefsLegend",
    title: "Canais de envio",
    description: "App, push, email e WhatsApp — cada um com sua cor.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "notifications-section",
    kind: "showcase",
    scene: "notif-prefs",
    highlight: "notifPrefsFirstSection",
    title: "Tipos de notificação",
    description: "Habilite ou desabilite por tipo de evento.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "notifications-toggles",
    kind: "showcase",
    scene: "notif-prefs",
    highlight: "notifPrefsChannelToggles",
    title: "Toggles",
    description: "Quatro pontos coloridos = quatro canais. Toque para ativar/desativar.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "preferences-replay",
    kind: "showcase",
    scene: "preferencias",
    highlight: "preferencesReplayButton",
    title: "Refazer tutorial",
    description: "Sempre que quiser revisar este tutorial, é por aqui.",
    placement: "top",
    autoAdvanceMs: 3000,
  },
  {
    id: "perfil-photo",
    kind: "showcase",
    scene: "perfil",
    highlight: "perfilPhoto",
    title: "Foto de perfil",
    description: "Toque na câmera para trocar sua foto.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "perfil-info",
    kind: "showcase",
    scene: "perfil",
    highlight: "perfilAddress",
    title: "Endereço",
    description: "Mantenha seu endereço atualizado.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "perfil-sizes",
    kind: "showcase",
    scene: "perfil",
    highlight: "perfilSizes",
    title: "Tamanhos",
    description: "Camisa, calça e bota — usado pelo RH ao solicitar uniformes.",
    placement: "top",
    autoAdvanceMs: 3000,
  },
  {
    id: "completion",
    kind: "narration",
    scene: "home",
    title: "Tudo pronto!",
    description: "Você concluiu o tour pelo Ankaa. Bom trabalho!",
    placement: "center",
    celebrate: true,
    ctaLabel: "Concluir",
  },
];
