import type { TutorialStep } from "../engine-types";

export const taskDetailSteps: TutorialStep[] = [
  {
    id: "task-header",
    kind: "showcase",
    scene: "task-detail",
    highlight: "taskHeader",
    title: "Cabeçalho da tarefa",
    description: "Nome, serial, categoria e status no topo.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "task-info-card",
    kind: "showcase",
    scene: "task-detail",
    highlight: "taskInfoCard",
    title: "Informações",
    description: "Cliente, cidade, setor e responsáveis pela tarefa.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "task-commission-badge",
    kind: "showcase",
    scene: "task-detail",
    highlight: "taskCommissionBadge",
    title: "Tarefa comissionável",
    description: "Esta tarefa gera comissão. Conclua para garantir o bônus.",
    placement: "top",
    autoAdvanceMs: 3000,
  },
  {
    id: "task-dates-card",
    kind: "showcase",
    scene: "task-detail",
    highlight: "taskDatesCard",
    title: "Datas",
    description: "Entrada, prazo final e previsão atual.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "task-services-card",
    kind: "showcase",
    scene: "task-detail",
    highlight: "taskServicesCard",
    title: "Serviços",
    description: "Lista de ordens de serviço da tarefa, com status individual.",
    placement: "top",
    autoAdvanceMs: 3000,
  },
  {
    id: "task-service-observation",
    kind: "showcase",
    scene: "task-detail",
    highlight: "taskServiceObservationIndicator",
    title: "Observação na OS",
    description: "Quando um serviço tem observação, este ícone aparece.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "task-paints-general",
    kind: "showcase",
    scene: "task-detail",
    highlight: "taskPaintsCard",
    title: "Tinta geral",
    description: "A cor principal da pintura, com marca e tipo.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "task-ground-paints",
    kind: "showcase",
    scene: "task-detail",
    highlight: "taskGroundPaintsCard",
    title: "Fundos",
    description: "Tintas de fundo aplicadas antes da pintura final.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "task-logo-paints",
    kind: "showcase",
    scene: "task-detail",
    highlight: "taskLogoPaintsCard",
    title: "Tintas de logo",
    description: "Cores usadas nos logos e detalhes.",
    placement: "bottom",
    autoAdvanceMs: 3000,
  },
  {
    id: "task-observations-table",
    kind: "showcase",
    scene: "task-detail",
    highlight: "taskObservationsTable",
    title: "Observações",
    description: "Observações registradas durante a produção.",
    placement: "top",
    autoAdvanceMs: 3000,
  },
  {
    id: "task-artworks",
    kind: "showcase",
    scene: "task-detail",
    highlight: "taskArtworksGallery",
    title: "Artworks",
    description: "Layouts de aprovação dos clientes.",
    placement: "top",
    autoAdvanceMs: 3000,
  },
  {
    id: "task-cuts-table",
    kind: "showcase",
    scene: "task-detail",
    highlight: "taskCutsTable",
    title: "Recortes",
    description: "Vinis e stencils utilizados.",
    placement: "top",
    autoAdvanceMs: 3000,
  },
  {
    id: "task-airbrushings-table",
    kind: "showcase",
    scene: "task-detail",
    highlight: "taskAirbrushingsTable",
    title: "Aerografias",
    description: "Detalhes pintados à mão registrados aqui.",
    placement: "top",
    autoAdvanceMs: 3000,
  },
  {
    id: "task-back-to-list",
    kind: "interactive",
    scene: "task-detail",
    highlight: "chromeHeaderBack",
    title: "Voltar",
    description: "Toque na seta para voltar à lista.",
    expectedAction: "tap",
    placement: "bottom",
    pulseTarget: true,
  },
];
