import { useState, useEffect } from "react";
import { View, StyleSheet, TouchableOpacity, Modal, ActivityIndicator, Pressable, Keyboard, Alert } from "react-native";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm, Controller } from "react-hook-form";
import { z } from "zod";
import { ThemedText } from "@/components/ui";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Text } from "@/components/ui/text";
import { useTheme } from "@/lib/theme";
import { fontSize, fontWeight } from "@/constants/design-system";
import { formSpacing, formLayout } from "@/constants/form-styles";
import { useTaskMutations } from "@/hooks/useTask";
import { TASK_STATUS } from "@/constants";
import { queryClient } from "@/lib/query-client";
// import { showToast } from "@/components/ui/toast";
import type { Task } from "@/types";
import {
  IconCopy,
  IconX,
} from "@tabler/icons-react-native";

const duplicateSchema = z.object({
  serialNumber: z
    .string()
    .nullable()
    .optional()
    .transform((val) => val?.trim().toUpperCase() || null),
  plate: z
    .string()
    .nullable()
    .optional()
    .transform((val) => val?.trim().toUpperCase() || null),
  chassisNumber: z
    .string()
    .nullable()
    .optional()
    .transform((val) => val?.trim().replace(/\s/g, "").toUpperCase() || null),
});

type DuplicateFormData = z.infer<typeof duplicateSchema>;

interface TaskDuplicateModalProps {
  visible: boolean;
  onClose: () => void;
  task: Task | null;
  onSuccess?: (task: Task) => void;
}

export function TaskDuplicateModal({
  visible,
  onClose,
  task,
  onSuccess,
}: TaskDuplicateModalProps) {
  const { colors } = useTheme();
  const { createAsync } = useTaskMutations();
  const [isSubmitting, setIsSubmitting] = useState(false);

  const {
    control,
    handleSubmit,
    formState: { errors },
    reset,
  } = useForm<DuplicateFormData>({
    resolver: zodResolver(duplicateSchema),
    defaultValues: {
      serialNumber: "",
      plate: "",
      chassisNumber: "",
    },
    mode: "onChange",
  });

  // Reset form when modal opens
  useEffect(() => {
    if (visible) {
      reset({
        serialNumber: "",
        plate: "",
        chassisNumber: "",
      });
    }
  }, [visible, reset]);

  const onSubmit = async (data: DuplicateFormData) => {
    if (!task) {
      Alert.alert("Erro", "Nenhuma tarefa selecionada");
      return;
    }

    setIsSubmitting(true);
    try {
      // Create new task with all the same data except:
      // - New serial number, plate and chassis from form
      // - Reset status to WAITING_PRODUCTION
      // - Reset dates
      // - New ID (generated by API)
      const newTaskData: any = {
        // Basic fields
        name: task.name,
        status: TASK_STATUS.WAITING_PRODUCTION,
        // Sanitize serialNumber - remove invalid characters, keep only A-Z, 0-9, and -
        serialNumber: (data.serialNumber || String(task.serialNumber || "")).replace(/[^A-Z0-9-]/gi, "").toUpperCase(),
        details: task.details,
        entryDate: task.entryDate,
        term: task.term,
        startedAt: null,
        finishedAt: null,
        paintId: task.paintId,
        customerId: task.customerId,
        sectorId: task.sectorId,
        commission: task.commission,
        budgetIds: task.budgets?.map((b: any) => b.id) || [],
        invoiceIds: task.invoices?.map((i: any) => i.id) || [],
        receiptIds: task.receipts?.map((r: any) => r.id) || [],

        // Relations - copy artwork and paint IDs
        artworkIds: task.artworks?.map((file) => file.id),
        paintIds: task.logoPaints?.map((paint) => paint.id),

        // Complex relations - copy nested data
        observation: task.observation
          ? {
              description: task.observation.description,
              artworkIds: task.observation.artworks?.map((file: any) => file.id) || [],
            }
          : null,

        services: task.serviceOrders?.map((service) => ({
          status: service.status,
          statusOrder: service.statusOrder,
          description: service.description,
          startedAt: null,
          finishedAt: null,
        })),

        // Truck with new plate and chassis
        truck: {
          plate: data.plate || task.truck?.plate || null,
          chassisNumber: data.chassisNumber || task.truck?.chassisNumber || null,
          model: task.truck?.model || "",
          manufacturer: task.truck?.manufacturer || "OTHER",
          xPosition: null,
          yPosition: null,
        },

        // Note: cuts are not duplicated
        cut: null,
      };

      const result = await createAsync(newTaskData);

      queryClient.invalidateQueries({ queryKey: ["tasks"] });

      // API client already shows success alert

      onSuccess?.(result.data);
      reset();
      onClose();
    } catch (error: any) {
      console.error("[TaskDuplicateModal] Error:", error);
      // API client already shows error alert
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleClose = () => {
    if (isSubmitting) return;
    reset();
    onClose();
  };

  return (
    <Modal
      visible={visible}
      animationType="fade"
      transparent={true}
      onRequestClose={handleClose}
    >
      <Pressable style={styles.overlay} onPress={handleClose}>
        <Pressable style={[styles.modal, { backgroundColor: colors.background }]} onPress={() => Keyboard.dismiss()}>
          {/* Header */}
          <View style={[styles.header, { borderBottomColor: colors.border }]}>
            <View style={styles.headerContent}>
              <IconCopy size={20} color={colors.primary} />
              <ThemedText style={styles.headerTitle}>Duplicar Tarefa</ThemedText>
            </View>
            <TouchableOpacity
              style={[styles.closeButton, { backgroundColor: colors.muted }]}
              onPress={handleClose}
              disabled={isSubmitting}
            >
              <IconX size={18} color={colors.foreground} />
            </TouchableOpacity>
          </View>

          {/* Content */}
          <View style={styles.content}>
            {/* Task name */}
            <ThemedText style={[styles.taskName, { color: colors.mutedForeground }]} numberOfLines={1}>
              {task?.name}
            </ThemedText>

            {/* Serial Number Field */}
            <View style={styles.formField}>
              <ThemedText style={styles.label}>Numero de Serie</ThemedText>
              <Controller
                control={control}
                name="serialNumber"
                render={({ field: { onChange, value } }) => (
                  <Input
                    value={value || ""}
                    onChangeText={(text) => onChange(text.toUpperCase())}
                    placeholder="Ex: ABC-123"
                    autoCapitalize="characters"
                    error={errors.serialNumber?.message}
                  />
                )}
              />
              {errors.serialNumber && (
                <ThemedText style={[styles.errorText, { color: colors.destructive }]}>
                  {errors.serialNumber.message}
                </ThemedText>
              )}
            </View>

            {/* Plate Field */}
            <View style={styles.formField}>
              <ThemedText style={styles.label}>Placa</ThemedText>
              <Controller
                control={control}
                name="plate"
                render={({ field: { onChange, value } }) => (
                  <Input
                    value={value || ""}
                    onChangeText={(text) => onChange(text.toUpperCase())}
                    placeholder="Ex: ABC1D23"
                    autoCapitalize="characters"
                  />
                )}
              />
            </View>

            {/* Chassis Number Field */}
            <View style={styles.formField}>
              <ThemedText style={styles.label}>Numero do Chassi</ThemedText>
              <Controller
                control={control}
                name="chassisNumber"
                render={({ field: { onChange, value } }) => (
                  <Input
                    value={value || ""}
                    onChangeText={(text) => onChange(text.toUpperCase())}
                    placeholder="Ex: 9BWZZZ377VT004251"
                    autoCapitalize="characters"
                  />
                )}
              />
            </View>
          </View>

          {/* Footer */}
          <View style={[styles.footer, { borderTopColor: colors.border }]}>
            <View style={styles.buttonWrapper}>
              <Button
                variant="outline"
                onPress={handleClose}
                disabled={isSubmitting}
              >
                <IconX size={18} color={colors.mutedForeground} />
                <Text style={styles.buttonText}>Cancelar</Text>
              </Button>
            </View>

            <View style={styles.buttonWrapper}>
              <Button
                variant="default"
                onPress={handleSubmit(onSubmit)}
                disabled={isSubmitting || !task}
              >
                {isSubmitting ? (
                  <ActivityIndicator size="small" color={colors.primaryForeground} />
                ) : (
                  <IconCopy size={18} color={colors.primaryForeground} />
                )}
                <Text style={[styles.buttonText, { color: colors.primaryForeground }]}>
                  {isSubmitting ? "Duplicando..." : "Duplicar"}
                </Text>
              </Button>
            </View>
          </View>
        </Pressable>
      </Pressable>
    </Modal>
  );
}

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  modal: {
    width: "100%",
    maxWidth: 400,
    borderRadius: 16,
    overflow: "hidden",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: "600",
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  content: {
    padding: 16,
    gap: 12,
  },
  taskName: {
    fontSize: fontSize.sm,
    textAlign: "center",
  },
  formField: {
    gap: 6,
  },
  label: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
  },
  errorText: {
    fontSize: 12,
    marginTop: 2,
  },
  footer: {
    flexDirection: "row",
    gap: formSpacing.rowGap,
    padding: formSpacing.actionBarPadding,
    borderTopWidth: formLayout.borderWidth,
  },
  buttonWrapper: {
    flex: 1,
  },
  buttonText: {
    fontSize: 15,
    fontWeight: "600",
  },
});
