/* eslint-disable no-console */
/**
 * generate-route-privileges.ts
 *
 * Walks the `src/app/(tabs)/` filesystem tree and emits
 * `src/utils/route-privileges.generated.ts` — a map of every route
 * to the privilege keys derived from its directory ancestry.
 *
 * Heuristic mapping (top-level directory → privilege):
 *   administracao                 → ADMIN
 *   estoque                       → WAREHOUSE
 *   producao                      → PRODUCTION
 *   pintura                       → WAREHOUSE
 *   recursos-humanos              → HUMAN_RESOURCES
 *   pessoal | meu-pessoal         → BASIC
 *   financeiro                    → FINANCIAL
 *   servidor                      → ADMIN
 *   manutencao                    → MAINTENANCE
 *   integracoes                   → ADMIN
 *   inicio | catalogo | favorites → BASIC
 *
 * Special cases (HR `cargos/cadastrar` requires ADMIN, etc.) live in
 * `src/utils/route-privileges.overrides.ts`. Run-time merge:
 *   final = { ...generated, ...overrides }
 *
 * IMPORTANT: this script is for tooling only — it does NOT auto-run.
 * Invoke manually after large refactors that add/move screen files:
 *   npx ts-node scripts/generate-route-privileges.ts
 *
 * The committed `route-privileges.generated.ts` was hand-seeded for v1
 * to keep the foundation pass dependency-free. CI should run this script
 * and fail if the generated file drifts from the on-disk tree.
 */

import * as fs from "node:fs";
import * as path from "node:path";

type Privilege =
  | "ADMIN"
  | "WAREHOUSE"
  | "PRODUCTION"
  | "HUMAN_RESOURCES"
  | "FINANCIAL"
  | "MAINTENANCE"
  | "BASIC"
  | "DESIGNER"
  | "COMMERCIAL"
  | "LOGISTIC"
  | "PRODUCTION_MANAGER"
  | "PLOTTING"
  | "EXTERNAL";

const TOP_LEVEL_PRIVILEGE: Record<string, Privilege> = {
  administracao: "ADMIN",
  estoque: "WAREHOUSE",
  producao: "PRODUCTION",
  pintura: "WAREHOUSE",
  "recursos-humanos": "HUMAN_RESOURCES",
  pessoal: "BASIC",
  "meu-pessoal": "BASIC",
  financeiro: "FINANCIAL",
  servidor: "ADMIN",
  manutencao: "MAINTENANCE",
  integracoes: "ADMIN",
  inicio: "BASIC",
  catalogo: "BASIC",
  favorites: "BASIC",
  notifications: "BASIC",
  perfil: "BASIC",
  configuracoes: "BASIC",
  "minha-equipe": "BASIC",
  "meu-pessoal-novo": "BASIC",
};

const ROUTE_FILE_NAMES = new Set(["index.tsx", "index.ts"]);
const SCREEN_EXTENSIONS = [".tsx"];

function toRoute(absPath: string, root: string): string {
  let rel = path.relative(root, absPath);
  // Strip extension
  for (const ext of SCREEN_EXTENSIONS) {
    if (rel.endsWith(ext)) rel = rel.slice(0, -ext.length);
  }
  // Strip /index suffix
  if (rel.endsWith("/index")) rel = rel.slice(0, -"/index".length);
  // Convert path segments to URL segments (no escaping needed for [param])
  return "/(tabs)/" + rel.split(path.sep).join("/");
}

function privilegeFor(routePath: string): Privilege {
  // routePath = "/(tabs)/<top>/<...>"
  const segments = routePath.replace("/(tabs)/", "").split("/");
  const top = segments[0];
  return TOP_LEVEL_PRIVILEGE[top] ?? "ADMIN";
}

function walk(dir: string, out: string[]): void {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const e of entries) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) {
      walk(p, out);
    } else if (e.isFile()) {
      if (SCREEN_EXTENSIONS.some((ext) => e.name.endsWith(ext))) {
        // Skip layout / +not-found / private-prefixed files
        if (e.name.startsWith("_") || e.name.startsWith("+")) continue;
        out.push(p);
      }
    }
  }
}

function main(): void {
  const root = path.resolve(__dirname, "..", "src", "app", "(tabs)");
  if (!fs.existsSync(root)) {
    console.error(`Tabs root not found at ${root}`);
    process.exit(1);
  }

  const files: string[] = [];
  walk(root, files);

  const map: Record<string, Privilege> = {};
  for (const file of files) {
    const route = toRoute(file, root);
    map[route] = privilegeFor(route);
  }

  const sortedKeys = Object.keys(map).sort();
  const lines: string[] = [];
  lines.push("/* eslint-disable */");
  lines.push("// AUTO-GENERATED by scripts/generate-route-privileges.ts — DO NOT EDIT BY HAND.");
  lines.push("// Hand-tuned exceptions live in route-privileges.overrides.ts.");
  lines.push("");
  lines.push('import { SECTOR_PRIVILEGES } from "@/constants";');
  lines.push("");
  lines.push("export type GeneratedPrivilege = keyof typeof SECTOR_PRIVILEGES;");
  lines.push("");
  lines.push("export const GENERATED_ROUTE_PRIVILEGES: Record<string, GeneratedPrivilege> = {");
  for (const k of sortedKeys) {
    lines.push(`  ${JSON.stringify(k)}: "${map[k]}",`);
  }
  lines.push("};");
  lines.push("");

  const outPath = path.resolve(__dirname, "..", "src", "utils", "route-privileges.generated.ts");
  fs.writeFileSync(outPath, lines.join("\n"), "utf8");
  console.log(`Wrote ${sortedKeys.length} route entries to ${outPath}`);
}

if (require.main === module) {
  main();
}
