import React from "react";
import { View, TouchableOpacity, StyleSheet, ViewStyle } from "react-native";
import { usePathname, useRouter, useSegments } from "expo-router";
import { ThemedText } from "./themed-text";
import { useTheme } from "@/lib/theme";
import { spacing, fontSize, fontWeight, borderRadius } from "@/constants/design-system";
import { IconChevronRight, IconHome } from "@tabler/icons-react-native";
import { isRouteRegistered, getFallbackRoute } from "@/utils/route-validator";

export interface BreadcrumbSegment {
  label: string;
  path: string;
  isLast?: boolean;
}

export interface BreadcrumbProps {
  /**
   * Manual segments to display (overrides auto-generated segments)
   */
  segments?: BreadcrumbSegment[];
  /**
   * Show home icon as first segment
   */
  showHome?: boolean;
  /**
   * Maximum number of segments to show before truncating
   */
  maxSegments?: number;
  /**
   * Custom style for the container
   */
  style?: ViewStyle;
  /**
   * Callback when a segment is pressed
   */
  onSegmentPress?: (segment: BreadcrumbSegment) => void;
}

/**
 * Route label mapping for common routes
 * Maps route segments to human-readable labels
 */
export const ROUTE_LABELS: Record<string, string> = {
  // Main sections
  "(tabs)": "",
  "administration": "Administração",
  "production": "Produção",
  "inventory": "Estoque",
  "painting": "Pintura",
  "human-resources": "Recursos Humanos",
  "personal": "Pessoal",
  "my-team": "Meu Pessoal",
  "server": "Servidor",
  "integrations": "Integrações",
  "maintenance": "Manutenção",
  "financial": "Financeiro",
  "catalog": "Catálogo",
  "dashboard": "Painel",

  // Common entities
  "customers": "Clientes",
  "collaborators": "Colaboradores",
  "users": "Usuários",
  "sectors": "Setores",
  "notifications": "Notificações",
  "files": "Arquivos",

  // Production
  "schedule": "Cronograma",
  "service-orders": "Ordens de Serviço",
  "services": "Serviços",
  "trucks": "Caminhões",
  "garages": "Garagens",
  "cutting": "Recorte",
  "airbrushing": "Aerografia",
  "paints": "Tintas",
  "observations": "Observações",
  "history": "Histórico",
  "on-hold": "Em Espera",

  // Inventory
  "products": "Produtos",
  "suppliers": "Fornecedores",
  "orders": "Pedidos",
  "movements": "Movimentações",
  "borrows": "Empréstimos",
  "ppe": "EPI",
  "external-withdrawals": "Retiradas Externas",

  // Painting
  "formulas": "Fórmulas",
  "components": "Componentes",
  "paint-types": "Tipos de Tinta",
  "paint-brands": "Marcas de Tinta",
  "paint-grounds": "Fundos",

  // HR
  "employees": "Colaboradores",
  "positions": "Cargos",
  "holidays": "Feriados",
  "vacations": "Férias",
  "performance-levels": "Níveis de Desempenho",
  "warnings": "Advertências",
  "payroll": "Folha de Pagamento",
  "bonus": "Bonificações",
  "time-clock": "Controle de Ponto",

  // Personal
  "my-profile": "Meu Perfil",
  "my-notifications": "Minhas Notificações",
  "my-vacations": "Minhas Férias",
  "my-warnings": "Meus Avisos",
  "my-borrows": "Meus Empréstimos",
  "my-ppes": "Meus EPIs",
  "my-holidays": "Meus Feriados",
  "preferences": "Preferências",

  // Server
  "backups": "Backups",
  "change-logs": "Registros de Alterações",
  "deployments": "Implantações",
  "logs": "Logs",
  "metrics": "Métricas",
  "system-users": "Usuários do Sistema",

  // Actions
  "list": "Listar",
  "create": "Cadastrar",
  "edit": "Editar",
  "details": "Detalhes",
  "batch-operations": "Operações em Lote",

  // Common
  "home": "Início",
  "settings": "Configurações",
};

/**
 * Generates breadcrumb segments from the current route
 */
function useAutoGeneratedSegments(): BreadcrumbSegment[] {
  const pathname = usePathname();
  const segments = useSegments();

  return React.useMemo(() => {
    const breadcrumbs: BreadcrumbSegment[] = [];
    let currentPath = "";

    segments.forEach((segment, index) => {
      // Skip empty segments and route groups
      if (!segment || segment.startsWith("(") || segment === "") return;

      // Build path incrementally
      currentPath += `/${segment}`;

      // Check if this is a dynamic segment (starts with [ or is a UUID/number)
      const isDynamic = segment.startsWith("[") || /^[a-f0-9-]{36}$/i.test(segment) || /^\d+$/.test(segment);

      // Get label from mapping or use segment as-is
      let label = ROUTE_LABELS[segment] || segment;

      // For dynamic segments, try to get a better label
      if (isDynamic) {
        const prevSegment = segments[index - 1];
        const entityType = ROUTE_LABELS[prevSegment] || prevSegment;
        label = `${entityType}`;
      }

      // Capitalize first letter if not in mapping
      if (!ROUTE_LABELS[segment]) {
        label = label.charAt(0).toUpperCase() + label.slice(1);
      }

      breadcrumbs.push({
        label,
        path: currentPath,
        isLast: index === segments.length - 1,
      });
    });

    return breadcrumbs;
  }, [segments, pathname]);
}

/**
 * Breadcrumb navigation component
 * Shows the current navigation path with clickable segments
 */
export function Breadcrumb({
  segments: manualSegments,
  showHome = true,
  maxSegments = 5,
  style,
  onSegmentPress,
}: BreadcrumbProps) {
  const { colors } = useTheme();
  const router = useRouter();
  const autoSegments = useAutoGeneratedSegments();

  const segments = manualSegments || autoSegments;

  // Filter out empty segments
  const filteredSegments = segments.filter((s) => s.label && s.label.trim() !== "");

  // Truncate if too many segments
  const displaySegments =
    filteredSegments.length > maxSegments
      ? [
          ...filteredSegments.slice(0, 2),
          { label: "...", path: "", isLast: false },
          ...filteredSegments.slice(-2),
        ]
      : filteredSegments;

  const handleSegmentPress = (segment: BreadcrumbSegment) => {
    if (segment.isLast || segment.path === "") return;

    if (onSegmentPress) {
      onSegmentPress(segment);
    } else {
      // Validate route before navigation
      const routePath = segment.path.replace(/^\/?\(tabs\)\//, "");
      if (!isRouteRegistered(routePath)) {
        console.warn(`[Breadcrumb] Route "${routePath}" is not registered. Falling back to home.`);
        router.push(getFallbackRoute() as any);
        return;
      }
      router.push(segment.path as any);
    }
  };

  const handleHomePress = () => {
    router.push("/(tabs)/home" as any);
  };

  if (displaySegments.length === 0 && !showHome) {
    return null;
  }

  return (
    <View style={[styles.container, style]}>
      {/* Home button */}
      {showHome && (
        <>
          <TouchableOpacity
            onPress={handleHomePress}
            style={styles.segment}
            activeOpacity={0.7}
          >
            <IconHome size={16} color={colors.mutedForeground} />
          </TouchableOpacity>
          {displaySegments.length > 0 && (
            <IconChevronRight size={14} color={colors.mutedForeground} style={styles.separator} />
          )}
        </>
      )}

      {/* Breadcrumb segments */}
      {displaySegments.map((segment, index) => (
        <React.Fragment key={`${segment.path}-${index}`}>
          {segment.path === "" ? (
            // Ellipsis (non-clickable)
            <View style={styles.segment}>
              <ThemedText
                style={[
                  styles.segmentText,
                  { color: colors.mutedForeground },
                ]}
              >
                {segment.label}
              </ThemedText>
            </View>
          ) : (
            // Regular segment
            <TouchableOpacity
              onPress={() => handleSegmentPress(segment)}
              style={styles.segment}
              activeOpacity={segment.isLast ? 1 : 0.7}
              disabled={segment.isLast}
            >
              <ThemedText
                style={[
                  styles.segmentText,
                  {
                    color: segment.isLast ? colors.foreground : colors.mutedForeground,
                    fontWeight: segment.isLast ? fontWeight.semibold : fontWeight.normal,
                  },
                ]}
                numberOfLines={1}
              >
                {segment.label}
              </ThemedText>
            </TouchableOpacity>
          )}

          {/* Separator */}
          {index < displaySegments.length - 1 && (
            <IconChevronRight size={14} color={colors.mutedForeground} style={styles.separator} />
          )}
        </React.Fragment>
      ))}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    gap: spacing.xs,
  },
  segment: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: borderRadius.sm,
    maxWidth: 200,
  },
  segmentText: {
    fontSize: fontSize.sm,
  },
  separator: {
    marginHorizontal: spacing.xs / 2,
  },
});

Breadcrumb.displayName = "Breadcrumb";
